language: node_js
node_js:
  - "12.18.2"
cache: npm

install:
  - npm install

script:
  - npm install run build

deploy:
  provider: pages
  cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master