language: node_js
node_js:
  - "12.18.2"
cache: npm

install:
  - npm install

script:
  - npm install run build

deploy:
  - provider: pages
    local_dir: ./build/
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      - branch: master