language: node_js
node_js:
  - "12.18.2"
cache: yarn

install:
  - yarn install

script:
  - yarn test

before_deploy:
  - yarn build

deploy:
  provider: pages
  cleanup: true
  github-token: $GITHUB_TOKEN
  repo: fernandoportilla1/fernandoportilla1.github.io
  keep-history: true
  target-branch: master
  local_dir: build
  on:
    branch: master