language: node_js
node_js:
  - "12.18.2"
cache: npm

env:
  - PUBLIC_URL=me/

install:
  - npm install

script:
  - npm run test
  - npm run build

deploy:
  provider: surge
  cleanup: true
  project: build
  provider: pages
  cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master