language: node_js
node_js:
  - "12.18.2"
cache: yarn

env:
  - PUBLIC_URL=me/

install:
  - yarn install

script:
  - yarn test

before_deploy:
  - yarn build

deploy:
  provider: pages
  cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master