language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm install run build

deploy:
  provider: pages
  cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master