language: node_js
node_js:
  - "12.18.2"
cache: npm

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./build/
  on:
    branch: master